# Generated by Django 4.2.6 on 2024-01-16 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_alter_crop_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crop',
            name='image',
        ),
        migrations.AddField(
            model_name='crop',
            name='image_blob',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
